-- Cria a tabela
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  content text not null,
  created_at timestamp with time zone default now()
);

-- Ativa Realtime nessa tabela
alter publication supabase_realtime add table public.messages;